kind: pipeline
name: Drone

steps:
 - name: compile
   image: dereference23/kernel_arm64:clang
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
     kernal:
       from_secret: kernal
   commands:
#       - apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison
      - git config --global user.name "me"
      - git config --global user.email "me@gmail.com"
      - git config --global color.ui false
      - chmod -R 0777 .
      - git clone https://github.com/FutureDrones/kernel kernel/
      - cd kernel
      - bash complex.sh blueline
